name: Build and Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**' 

jobs:
  llvm-17:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install LLVM and Clang
      run: sudo apt-get update && sudo apt-get install -y llvm-18 clang-18

    - name: Checking LLVM and Clang
      run: clang-18 --version && opt-18 --version && which opt && which opt-18

    - name: Configure CMake
      run: cmake -B build -DLLVM_DIR=/usr/lib/llvm-18/cmake

    - name: Build
      run: cmake --build build -t run_test

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: build


