name: Build and Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**' 

jobs:
  llvm-17:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install LLVM and Clang
      run: wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 17

    - name: Replace default clang
      run: |
        sudo mv /usr/bin/clang /usr/bin/clang-old
        sudo mv /usr/bin/clang++ /usr/bin/clang++-old
        sudo ln -s /usr/bin/clang-17 /usr/bin/clang
        sudo ln -s /usr/bin/clang++-17 /usr/bin/clang++
        sudo ln -s /usr/bin/opt-17 /usr/bin/opt

    - name: Check LLVM and Clang
      run: clang --version && opt --version 

    - name: Configure CMake with Clang
      run: cmake -B build -DLLVM_DIR=/usr/lib/llvm-17/cmake

    - name: Build
      run: cmake --build build -t run_test


