name: Build and Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**' 

jobs:
  llvm-17:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v2
      with:
        version: "17"

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Debug
      run: opt --version && ls build && pwd

    - name: Run Tests
      run: cmake --build build -t run_test